### ISSUE TITLE
malloc3.c crashes

### ISSUE THREAD

**Issue by SohumB** [pyroscope-io/pyroscope-python#7]
Hi there! I introduced pyroscope to our python app, and it causes repeated crashes:

```
python3: malloc.c:2539: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
```

I understand this isn't hugely helpful as a repro, but this app is ... large :) If there are targeted questions I can answer them!

**Comment by omarabid** [comment]
@SohumB Could you describe more your setup? (OS/Hardware) Are you using the PIP Package or the command-line for profiling? If you are using the PIP package, does the same error happen with the command-line?

**Comment by SohumB** [comment]
Hm, it appears something has changed in the intervening fortnight and I can no longer reproduce this issue. I suspect it may have something to do with incorrectly built wheels, as `pypprof` is still crashing on me, but whatever it is, it is no longer your problem 😄
